use of TabTabGo and Add interface ISaveNotificatoin to save Notificaton to storage
TabTabGo/TabTabGo.WebStream pull request #6
Opened 2024-05-27 13:34 UTC by Mohammad-Sarya-Tulimat

ISaveWebStreamMessage:  it have same logic of  IPushEvent implementation of storage  
but it is other interface used with storage only so we can use it when we don't need to push all Messages to storage

2024-05-28 06:10 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage.EFCore/EfCoreStorageBuilder.cs
Remove Tabtabgo as prefix and add schema as option

2024-05-28 06:33 UTC, gmsamara requested changes
Few points
1- Use PageList and PageOption instead of PageResultBuilder and Page Paramters
2- I don't see a need to store Messages to database
3- Nee to add logic store messages to log

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage.EFCore/Mappers/UserNotificationMapper.cs
Remove TabTabGo as prefix table name and add option for schema

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage.EFCore/Mappers/NotificationMapper.cs
Remove TabTabGo as prefix table name and add option for schema

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/Module/PageingResult.cs
Use the standard PageList and PageOptions from TabTabGo.Core

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/Module/PagingParameters.cs
Use TabTabGo.Core PageOptions

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/QueryExt.cs
This nice to move to TabTabGo.Core

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/Repository/INotificationRepository.cs
rename UserId to userId

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/Services/INotificationServices.cs
Use PageList and PageOption

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/Services/PushToStorageService.cs
Still don't see a need for it

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/Services/PushToStorageSucessOnDecorator.cs
Still don't see a need

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/TabTabGo.WebStream/Model/WebStreamMessage.cs
Don't see a need for it

2024-05-28 06:33 UTC, gmsamara commented on server/src/TabTabGo.WebStream/TabTabGo.WebStream/TabTabGo.WebStream.csproj
Convert to .net8

2024-05-28 09:13 UTC, Mohammad-Sarya-Tulimat commented on server/src/TabTabGo.WebStream/TabTabGo.WebStream/Model/WebStreamMessage.cs
how ??

2024-05-28 09:14 UTC, Mohammad-Sarya-Tulimat commented on server/src/TabTabGo.WebStream/TabTabGo.WebStream/Model/WebStreamMessage.cs
is it the message object we pass in and out

2024-05-28 09:15 UTC, Mohammad-Sarya-Tulimat commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/Services/PushToStorageService.cs
simply, don't add it in configuration if you don't need it

2024-05-28 09:15 UTC, Mohammad-Sarya-Tulimat commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/Services/PushToStorageSucessOnDecorator.cs
simply, don't add it in configuration if you don't need it

2024-05-28 17:49 UTC, gmsamara approved these changes

2024-05-29 05:36 UTC, gmsamara requested changes
Still need to update INotificationRepository . the other changes can be done later

2024-05-29 05:36 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/Repository/INotificationUserRepository.cs
Why we need these function use what in GenericRepoository
 
     Task<List<NotificationUser>> FindByCriteriaAsync(List<Expression<Func<NotificationUser, bool>>> criteria, string orderBy,bool isDesc, CancellationToken cancellationToken = default);
        List<NotificationUser> FindByCriteria(List<Expression<Func<NotificationUser, bool>>> criteria, string orderBy, bool isDesc); 
        Task<PageList<NotificationUser>> FindByCriteriaAsync(List<Expression<Func<NotificationUser, bool>>> criteria, string orderBy, bool isDesc, int pageSize,int pageNumber, CancellationToken cancellationToken = default);
        PageList<NotificationUser> FindByCriteria(List<Expression<Func<NotificationUser, bool>>> criteria, string orderBy, bool isDesc, int pageSize, int pageNumber); 

Rename FInd to Get

2024-05-29 05:36 UTC, gmsamara commented on server/src/TabTabGo.WebStream/TabTabGo.WebStream.SignalR/TabTabGo.WebStream.SignalR.csproj
Still .net Standard2.0

2024-05-29 05:36 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage.EFCore/Repositories/EfNotificationRepository.cs
Still use builder and not use the TabTabGo.Core framework

2024-05-29 05:36 UTC, gmsamara commented on server/src/TabTabGo.WebStream/NotificationStorage/TabTabGo.WebStream.NotificationStorage/Repository/INotificationRepository.cs
still parameter name not changed

2024-05-29 09:39 UTC, gmsamara approved these changes

2024-05-29 09:40 UTC, merged